name: JaCoCo Test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        java: [8, 11, 17, 21, 23]
        experimental: [false]
        include:
          - java: 24-ea
            experimental: true

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Build with Maven
        run: mvn -Drat.skip=true package --errors --show-version --batch-mode --no-transfer-progress

      - name: Generate JaCoCo report
        run: mvn -Drat.skip=true clean test jacoco:report

      - name: Upload JaCoCo HTML report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report-${{ github.run_id }}
          path: target/site/jacoco/index.html
